### ISSUE TITLE
KeyError: 'IQA_performance'

### ISSUE THREAD

**Issue by splinter21** [lidq92/LinearityIQA#3]
CUDA_VISIBLE_DEVICES=0 python main.py --dataset KonIQ-10k --resize --exp_id 0 --lr 1e-4 -bs 8 -e 30 --ft_lr_ratio 0.1 --arch resnext101_32x8d --loss_type Lp --p 1 --q 2

after about one epoch?

Engine run is terminating due to exception: 'IQA_performance'.
……
  File "main.py", line 100, in epoch_event_function
    performance = evaluator.state.metrics['IQA_performance']
KeyError: 'IQA_performance'

**Comment by lidq92** [comment]
@splinter21 Do you modify the code? 
Keyword `IQA_performance` is defined before this line of the code.

You can search for `create_supervised_evaluator` to see whether you have modified the keyword name `IQA_performance` of the metrics in `create_supervised_evaluator(model, metrics={'IQA_performance': ...`

**Comment by splinter21** [comment]
Thanks, I have fixed it!

**Comment by miracleagi** [comment]
> Thanks, I have fixed it!



> @splinter21 Do you modify the code?
> Keyword `IQA_performance` is defined before this line of the code.
> 
> You can search for `create_supervised_evaluator` to see whether you have modified the keyword name `IQA_performance` of the metrics in `create_supervised_evaluator(model, metrics={'IQA_performance': ...`

I only add two lines
sys.path.append('apex')
after I source install the apex module. However, the problem still appears. I double checked the class name used in main.py and found no mismatch. Any advice?

**Comment by lidq92** [comment]
@ChuanchuanZheng  I have no idea why this happened since I did not encounter this problem in all machines in my group.

Maybe you could remove `sys.path.append('apex')` since It works for me without this line.

Finally, you may ask @splinter21 for help since he has fixed it.

@splinter21 Could you write your solution here? Thank you.

===
Update: 2020.9.27
After git cloning the repo, I installed a new environment by following the `README.md` and re-run the experiments, and everything looks well with `apex` installed from the current master branch.

**Comment by miracleagi** [comment]
> @ChuanchuanZheng I have no idea why this happened since I did not encounter this problem in all machines in my group.
> 
> Maybe you could remove `sys.path.append('apex')` since It works for me without this line.
> 
> Finally, you may ask @splinter21 for help since he has fixed it.
> 
> @splinter21 Could you write your solution here? Thank you.
> 
> ===
> Update: 2020.9.27
> After git cloning the repo, I installed a new environment by following the `README.md` and re-run the experiments, and everything looks well with `apex` installed from the current master branch.

@lidq92 I commented the `sys.path.append('apex')`, but the problem still appears. Further, I tried that two ways to install apex module, but got same results. 
@splinter21 Could you please share your solution? Great thanks.

**Comment by lidq92** [comment]
@ChuanchuanZheng This code works well under different Linux operation systems since I have tested it many times (from the beginning of cloning the code and installing a new environment to the end).

My only last suggestion is to make sure that you have correctly installed all the requirements.

Good luck.

**Comment by splinter21** [comment]
> > @ChuanchuanZheng I have no idea why this happened since I did not encounter this problem in all machines in my group.
> > Maybe you could remove `sys.path.append('apex')` since It works for me without this line.
> > Finally, you may ask @splinter21 for help since he has fixed it.
> > @splinter21 Could you write your solution here? Thank you.
> > ===
> > Update: 2020.9.27
> > After git cloning the repo, I installed a new environment by following the `README.md` and re-run the experiments, and everything looks well with `apex` installed from the current master branch.
> 
> @lidq92 I commented the `sys.path.append('apex')`, but the problem still appears. Further, I tried that two ways to install apex module, but got same results.
> @splinter21 Could you please share your solution? Great thanks.

sys.path.append('path-apex')
The path-apex is the the cloned source codes path, it should countains "requirements.txt", "setup.py", "LICENSE", "README.md", dir-"apex", dir-"examples" and etc..

**Comment by lidq92** [comment]
@splinter21 @ChuanchuanZheng If you have followed my `README.md` to install your `reprodcuibleresearch` environment, no need to add the code `sys.path.append('path-apex')`.
You would have successfully installed apex, and it would appear at the following path ` you_path_to_anaconda3/envs/reproducibleresearch/lib/python3.6/site-packages/apex`.

**Comment by miracleagi** [comment]
> @splinter21 @ChuanchuanZheng If you have followed my `README.md` to install your `reprodcuibleresearch` environment, no need to add the code `sys.path.append('path-apex')`.
> You would have successfully installed apex, and it would appear at the following path ` you_path_to_anaconda3/envs/reproducibleresearch/lib/python3.6/site-packages/apex`.

@lidq92 @splinter21 Thank you very much. I have fixed my problem. I reckon that the mismatch version of torch and apex may be the reason. Anyway, great thanks to you both.

**Comment by lidq92** [comment]
OK.
I am closing this issue now.

**Comment by lidq92** [comment]
KeyError: 'IQA_performance' is a problem because of the mismatch ignite version.
If you use 0.2.1 as in my original repo, there will be no error.
See https://github.com/pytorch/ignite/issues/1476 and #8
